### PR TITLE
TLS: detect duplicate known extensions

### LINKED ISSUE #5863: ClientHello extensions parse lack of inspection of repeatability
### Contact Details

small_town_123@163.com

### Version

5.5.1

### Description

When we tested TLS1.2 on the TLS handshake implementation part of wolfSSL,
we found that the Server lack of inspection of repeatability when parsing the
Extensions field of the ClientHello message, but responded normally.

This is inconsistent with the specification "There MUST NOT be more than one
extension of the same type." in section 7.4.1.4 of the RFC5246 documentation.

The resolution ambiguity is easily caused, and if the processing of an extension
is complex and consumes large resources, the malicious Client may attack the
Server by repeat someone Extensions.

### Reproduction steps

The problem can be verified by simply sending a ClientHello message to wolfSSL Server with duplicate extensions.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SparkiDev**
# Description

TLS specification requires that there not be more than one extension of the same type in a given extension block. E.g. ClientHello

Fixes #5863

# Testing

Added test case test_tls_exr_duplicate().

# Checklist

 - [x] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by SmallTown123** [comment]
Hello! Thank you for your reply! 

I have read the fixed code in tls.c, I think the handle method of 
TLSX semaphore is a very clever way.
But I still have a question about whether the fixed code can handle all of the extension 
repeat situation, or just for the recognizable extensions?

For example, if the extension type is more than 62 but is not **TLSX_RENEGOTIATION_INFO** 
and not **TLSX_KEY_QUIC_TP_PARAMS_DRAFT**,  Whether this situation can be handled correctly?

**Comment by SparkiDev** [comment]
Hi @SmallTown123,

Only 'known' extensions are checked for duplication.
Duplicates of other extensions will not have any impact on the library as they are ignored.

Sean

**Comment by SmallTown123** [comment]
Understand @SparkiDev, thank you for your reply.

Town

File: tests/api.c [hunk 1]
```diff
@@ -9132,6 +9132,113 @@ static int test_wolfSSL_wolfSSL_UseSecureRenegotiation(void)
...
+#endif
+
+/* Test the detection of duplicate known TLS extensions.
+ * Specifically in a ClientHello.
+ */
+static int test_tls_ext_duplicate(void)
+{
+    int res = TEST_SKIPPED;
+#if !defined(NO_WOLFSSL_SERVER) && (!defined(NO_RSA) || defined(HAVE_ECC))
+    unsigned char clientHelloDupTlsExt[] = {
```
Comment (dgarske) [inline tests/api.c:9176]: `const`?

File: src/tls.c [hunk 2]
```diff
@@ -11918,6 +11920,7 @@ int TLSX_Parse(WOLFSSL* ssl, const byte* input, word16 length, byte msgType,
 #if defined(WOLFSSL_TLS13) && (defined(HAVE_SESSION_TICKET) || !defined(NO_PSK))
     int pskDone = 0;
 #endif
+    byte seenType[SEMAPHORE_SIZE] = {0};    /* Seen known extensions. */
```
Comment (dgarske) [inline src/tls.c:11923]: Prefer XMEMSET vs ` = {0}` initializer (for portability).

File: tests/api.c [hunk 3]
```diff
@@ -9132,6 +9132,113 @@ static int test_wolfSSL_wolfSSL_UseSecureRenegotiation(void)
...
+    (void)ssl;
+    (void)buf;
+    (void)sz;
+    (void)ctx;
+
+    /* Force error return from wolfSSL_accept_TLSv13(). */
+    return WANT_WRITE;
+}
+/* Called when reading. */
+static int BufferInfoRecv(WOLFSSL* ssl, char* buf, int sz, void* ctx)
```
Comment (dgarske) [inline tests/api.c:9148]: Very nice hack for doing a server side only test to "recv" data! Nice work

**Review by dgarske — CHANGES_REQUESTED** [review]
This is excellent work and the core logic is solid (leverages our existing `semaphore` logic. Just a couple minor items of feedback.

File: tests/api.c (hunk 1 above)
Comment (SparkiDev) [reply tests/api.c:9176]: Assigning to msg.buffer which is not const.
Made it static.

File: src/tls.c (hunk 2 above)
Comment (SparkiDev) [reply src/tls.c:11923]: Fixed

**Review by dgarske — APPROVED** [review]
