### PR TITLE
Changing ALPN selection to a deterministic point in the handshake.

### LINKED ISSUE #5710: [Bug]: ALPN and SNI callbacks invoked in reverse order
### Contact Details

stefan@eissing.org

### Version

master

### Description

Registered application callbacks for SNI and ALPN TLS extensions are invoked in reverse order. Example:

```
   /* server side */
    wolfSSL_CTX_set_servername_callback(ctx, inspect_SNI);
    wolfSSL_CTX_set_alpn_select_cb(ctx, select_ALPN, NULL);
   /* perform TLS accept() with client providing values */
   /* 'select_ALPN' is called first, 'inspect_SNI' afterwards */
```

The order should be the other way around. This is a guaranteed API behaviour of OpenSSL.

## rationale

Servers differ in ALPN negotiation based on the selected SNI. For example, some domains might have `h2` enabled, others not. With the current behaviour, a server is unable to make the right decision. Even if its ALPN callback tries to access the SNI value, it is not available if the TLSX order in the client hello contains ALPN before SNI.

Servers might not only offer variations of HTTP, but serve totally different protocols based on the SNI chosen.

### Reproduction steps

A test case in the context of the wolfSSL quic test suite would look like this:

```
#if defined(HAVE_ALPN) && defined(HAVE_SNI)

static int inspect_SNI(WOLFSSL *ssl, int *ad, void *baton)
{
    char *stripe = baton;

    (void)ssl;
    *ad = 0;
    strcat(stripe, "S");
    return 0;
}

static int select_ALPN(WOLFSSL *ssl,
            const unsigned char **out,
            unsigned char *outlen,
            const unsigned char *in,
            unsigned int inlen,
            void *baton)
{
    char *stripe = baton;

    (void)ssl;
    (void)inlen;
    /* just select the first */
    *out = in + 1;
    *outlen = in[0];
    strcat(stripe, "A");
    return 0;
}

static int test_quic_alpn(int verbose) {
    WOLFSSL_CTX *ctx_c, *ctx_s;
    int ret = 0;
    QuicTestContext tclient, tserver;
    QuicConversation conv;
    char stripe[256];
    unsigned char alpn_protos[256];

    AssertNotNull(ctx_c = wolfSSL_CTX_new(wolfTLSv1_3_client_method()));
    AssertNotNull(ctx_s = wolfSSL_CTX_new(wolfTLSv1_3_server_method()));
    AssertTrue(wolfSSL_CTX_use_certificate_file(ctx_s, svrCertFile, WOLFSSL_FILETYPE_PEM));
    AssertTrue(wolfSSL_CTX_use_PrivateKey_file(ctx_s, svrKeyFile, WOLFSSL_FILETYPE_PEM));

    stripe[0] = '\0';
    wolfSSL_CTX_set_servername_callback(ctx_s, inspect_SNI);
    wolfSSL_CTX_set_servername_arg(ctx_s, stripe);
    wolfSSL_CTX_set_alpn_select_cb(ctx_s, select_ALPN, stripe);

    /* setup ssls */
    QuicTestContext_init(&tclient, ctx_c, "client", verbose);
    QuicTestContext_init(&tserver, ctx_s, "server", verbose);

    /* set SNI and ALPN callbacks on server side,
     * provide values on client side */
    wolfSSL_UseSNI(tclient.ssl, WOLFSSL_SNI_HOST_NAME,
                   "wolfssl.com", sizeof("wolfssl.com")-1);
    /* connect */
    QuicConversation_init(&conv, &tclient, &tserver);

    strcpy((char*)(alpn_protos + 1), "test");
    alpn_protos[0] = 4;
    wolfSSL_set_alpn_protos(tclient.ssl, alpn_protos, 5);

    QuicConversation_do(&conv);
    AssertIntEQ(tclient.output.len, 0);
    AssertIntEQ(tserver.output.len, 0);

    /* SNI callback needs to be called before ALPN callback */
    AssertStrEQ(stripe, "SA");

    QuicTestContext_free(&tclient);
    QuicTestContext_free(&tserver);

    wolfSSL_CTX_free(ctx_c);
    wolfSSL_CTX_free(ctx_s);
    printf("    test_quic_alpn: %s\n", (ret == 0)? passed : failed);

    return ret;
}
#endif /* defined(HAVE_ALPN) && defined(HAVE_SNI) */
```

### Relevant log output

```shell
# Running the test above fails with:
ERROR - tests/quic.c line 1245 failed with:
    expected: stripe == "SA"
    result:   "AS" != "SA"
```

### PR DESCRIPTION
**Pull request by icing**
# Description

SNI and ALPN callbacks are now called in a deterministic order during the handshake:

* ALPN selection is done *after* the SNI callback has been invoked. Meaning any config/CTX changes based on SNI evaluation see the correct values
* ALPN evaluation happens after all TLSX from a ClientHello have been parsed. This mean that the SNI value is always available, regardless of the extension ordering the client used.
* OpenSSL documents exactly this ordering as guaranteed in its API, meaning this PR increases compatibility. 

Fixes #5710

# Testing

Added a test to the quic unittest suite in `tests/quic.c`. `--enable-quic` needs to be configured.

# Checklist

 - [x] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by dgarske** [comment]
OK to test

File: tests/quic.c [hunk 1]
```diff
@@ -1174,6 +1174,88 @@ static int test_quic_server_hello(int verbose) {
     return ret;
 }
 
+#if defined(HAVE_ALPN) && defined(HAVE_SNI)
```
Comment (tim-weller-wolfssl) [inline tests/quic.c:1177]: When building with only `--enable-quic`, the new test is missing some of APIs available only when `--enable-opensslall` is configured:
```
/usr/bin/ld: tests/unit_test-quic.o: in function `test_quic_alpn':
.../wolfssl//tests/quic.c:1221: undefined reference to `wolfSSL_CTX_set_servername_callback'
/usr/bin/ld: .../wolfssl//tests/quic.c:1222: undefined reference to `wolfSSL_CTX_set_servername_arg'
collect2: error: ld returned 1 exit status
```
I'd recommend including `defined(OPENSSL_ALL)` in the conditions protecting this new test

**Review by tim-weller-wolfssl — CHANGES_REQUESTED** [review]

File: tests/quic.c (hunk 1 above)
Comment (icing) [reply tests/quic.c]: Ah, missed the outer `#ifdef' several pages above. Added by the recent push.

Comment (icing) [reply tests/quic.c]: Resolved the leak that was caused by an early return. All green now.

**Review by tim-weller-wolfssl — APPROVED** [review]

File: src/ssl.c [hunk 2]
```diff
@@ -3108,22 +3108,32 @@ int wolfSSL_ALPN_GetProtocol(WOLFSSL* ssl, char **protocol_name, word16 *size)
 
 int wolfSSL_ALPN_GetPeerProtocol(WOLFSSL* ssl, char **list, word16 *listSz)
 {
+    int i, len;
+    char *p;
+    byte *s;
+
     if (list == NULL || listSz == NULL)
```
Comment (haydenroche5) [inline src/ssl.c:3115]: Looks like this was a problem before your changes, but we aren't checking that ssl is not NULL here, and we should be.

File: src/ssl.c [hunk 3]
```diff
@@ -3108,22 +3108,32 @@ int wolfSSL_ALPN_GetProtocol(WOLFSSL* ssl, char **protocol_name, word16 *size)
...
+        || ssl->alpn_peer_requested_length == 0)
         return BUFFER_ERROR;
 
-    *listSz = (word16)XSTRLEN(ssl->alpn_client_list);
-    if (*listSz == 0)
-        return BUFFER_ERROR;
-
-    *list = (char *)XMALLOC((*listSz)+1, ssl->heap, DYNAMIC_TYPE_TLSX);
-    if (*list == NULL)
+    *listSz = ssl->alpn_peer_requested_length -1;
```
Comment (haydenroche5) [inline src/ssl.c:3122]: Why -1? Is it because alpn_peer_requested_length includes the null terminator? If so, please add a comment explaining that.

File: src/ssl.c [hunk 4]
```diff
@@ -3108,22 +3108,32 @@ int wolfSSL_ALPN_GetProtocol(WOLFSSL* ssl, char **protocol_name, word16 *size)
...
         return MEMORY_ERROR;
 
-    XSTRNCPY(*list, ssl->alpn_client_list, (*listSz)+1);
-    (*list)[*listSz] = 0;
+    for (i = 0, s = ssl->alpn_peer_requested, len = 0;
+         i < ssl->alpn_peer_requested_length;
+         p += len, i += len) {
+        if (i)
+            *p++ = ',';
+        len = s[i++];
```
Comment (haydenroche5) [inline src/ssl.c:3133]: Does alpn_peer_requested have a leading byte for each protocol to indicate the length of the following protocol string? That's what it seems like. If that's right, a comment explaining that here would be helpful.

File: src/tls.c [hunk 5]
```diff
@@ -1579,134 +1579,190 @@ static int TLSX_SetALPN(TLSX** extensions, const void* data, word16 size,
...
-        }
-    }
-#endif
-
+    /* No ALPN configured here */
     if (extension == NULL || extension->data == NULL) {
-        return isRequest ? 0
-                         : TLSX_HandleUnsupportedExtension(ssl);
+        extension = NULL;
+        goto cleanup;
```
Comment (haydenroche5) [inline src/tls.c:1600]: No new gotos in the code. Part of our coding standard. Please refactor.

File: src/tls.c [hunk 6]
```diff
@@ -1579,134 +1579,190 @@ static int TLSX_SetALPN(TLSX** extensions, const void* data, word16 size,
...
+int ALPN_Select(WOLFSSL *ssl)
+{
+    TLSX *extension;
+    const byte *sel = NULL;
+    byte sel_len = 0;
+    int r = 0;
+
+    WOLFSSL_ENTER("ALPN_Select");
+    if (ssl->alpn_peer_requested == NULL) {
+        goto cleanup;
```
Comment (haydenroche5) [inline src/tls.c:1649]: See above re: new gotos.

File: src/tls.c [hunk 7]
```diff
@@ -1579,134 +1579,190 @@ static int TLSX_SetALPN(TLSX** extensions, const void* data, word16 size,
...
+static int TLSX_ALPN_ParseAndSet(WOLFSSL *ssl, const byte *input, word16 length,
+                                 byte isRequest)
+{
+    word16  size = 0, offset = 0, wlen;
+    int     r = BUFFER_ERROR;
+    TLSX    *extension;
+    const byte *s;
+
+    if (OPAQUE16_LEN > length)
+        goto cleanup;
```
Comment (haydenroche5) [inline src/tls.c:1705]: Same comment about new gotos.

File: src/tls.c [hunk 8]
```diff
@@ -1579,134 +1579,190 @@ static int TLSX_SetALPN(TLSX** extensions, const void* data, word16 size,
...
+        wlen = *s++;
+        if (wlen == 0 || (s + wlen - input) > length)
+            goto cleanup;
+    }
+
+    if (isRequest) {
+        /* keep the list sent by peer, if this is from a request. We
+         * use it later in ALPN_Select() for evaluation. */
+        if (ssl->alpn_peer_requested != NULL)
+            XFREE(ssl->alpn_peer_requested, ssl->heap, DYNAMIC_TYPE_ALPN);
```
Comment (haydenroche5) [inline src/tls.c:1724]: XFREE checks for NULL, so you can remove the check on line 1723.

File: src/tls.c [hunk 9]
```diff
@@ -1579,134 +1579,190 @@ static int TLSX_SetALPN(TLSX** extensions, const void* data, word16 size,
...
+                goto cleanup;
+            }
+        }
+        /* If we had nothing configured, the response is unexpected */
+        else if (extension == NULL) {
+            r = TLSX_HandleUnsupportedExtension(ssl);
+            goto cleanup;
+        }
+        else {
+            /* have sth configured, but did not match. no error returned
```
Comment (haydenroche5) [inline src/tls.c:1759]: I don't understand this comment. What is sth?

**Review by haydenroche5 — CHANGES_REQUESTED** [review]

File: src/ssl.c (hunk 2 above)
Comment (icing) [reply src/ssl.c:3115]: added.

File: src/ssl.c (hunk 4 above)
Comment (icing) [reply src/ssl.c:3133]: see above.

File: src/tls.c (hunk 5 above)
Comment (icing) [reply src/tls.c]: Ah, was not aware of that law. Removed the gotos again.

File: src/tls.c (hunk 6 above)
Comment (icing) [reply src/tls.c]: see above

File: src/tls.c (hunk 7 above)
Comment (icing) [reply src/tls.c]: see above

File: src/tls.c (hunk 9 above)
Comment (icing) [reply src/tls.c]: removed.

File: src/tls.c (hunk 8 above)
Comment (icing) [reply src/tls.c:1714]: Added the reset of `ssl->alpn_peer_requested_length` to `0` here also.

**Review by haydenroche5 — APPROVED** [review]
Approved, but I'd like @SparkiDev to take a look at these changes before merging.

**Review by SparkiDev — APPROVED** [review]
