### PR TITLE
Cortex-M inline assembly: labels with unique number appended

### LINKED ISSUE #7645: [Bug]: error: symbol already defined with WOLFSSL_SP_ASM enabled on ARM Compiler v6 with high size optimization (-Oz)
### Contact Details

dgatien@intevaproducts.com

### Version

5.7.0

### Description

Compiled with Keil uVision on a Cortex-M3, several errors like this one are reported in the file sp_cortexm.c:
```
sp_cortexm.c(31511): error: symbol 'L_sp_256_sqr_8_store' is already defined
 31511 |     "L_sp_256_sqr_8_store:\n\t"
       |      ^
<inline asm>(50): note: instantiated into assembly here
   50 | L_sp_256_sqr_8_store:
      | ^
```
Options WOLFSSL_SP_ASM and WOLFSSL_SP_ARM_CORTEX_M_ASM are enabled.

The issue is due to the compiler setting using highest size optimization (-Oz option with armclang), as explained in the GCC compiler manual:
> Under certain circumstances, GCC may duplicate (or remove duplicates of) your assembly code when optimizing. This can lead to unexpected duplicate symbol errors during compilation if your asm code defines symbols or labels. Using ‘%=’ (see [AssemblerTemplate](https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html#AssemblerTemplate)) may help resolve this problem.

After adding '%=' in all the labels from sp_cortexm.c, the code is compiling properly, ie:
`    "L_sp_256_sqr_8_store%=:\n\t"`
```
#if defined(__GNUC__) || defined(__ICCARM__) || defined(__IAR_SYSTEMS_ICC__)
        "BGT	L_sp_256_sqr_8_store%=\n\t"
#else
        "BGT.N	L_sp_256_sqr_8_store%=\n\t"
#endif
```

### Reproduction steps

- Use the ARM compiler v6 (armclang) with highest size optimization (-Oz)
- Enable WOLFSSL_SP_ASM and WOLFSSL_SP_ARM_CORTEX_M_ASM options

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SparkiDev**
# Description

When functions are inlined, the labels need to be unique. Putting '%=' on the end of the label ensures that the compilers appends a unique number to the end.

Fixes #7645

# Testing

./configure '--disable-shared' 'LDFLAGS=--static' '--host=armv7m' 'CC=arm-linux-gnueabi-gcc' '--enable-sp' '--enable-sp-asm' '--enable-armasm=inline' 'host_alias=armv7m'

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

File: wolfcrypt/src/port/arm/thumb2-sha256-asm_c.c [hunk 1]
```diff
@@ -101,7 +101,7 @@ void Transform_Sha256_Len(wc_Sha256* sha256, const byte* data, word32 len)
         "STRD	r10, r11, [sp, #88]\n\t"
         /* Start of loop processing a block */
         "\n"
-    "L_SHA256_transform_len_begin:\n\t"
+    "L_SHA256_transform_len_begin%=:\n\t"
```
Comment (dgarske) [inline wolfcrypt/src/port/arm/thumb2-sha256-asm_c.c:104]: Have you confirmed this works with compilers like IAR? Let me know if you need some help testing that.

Comment (SparkiDev) [reply wolfcrypt/src/port/arm/thumb2-sha256-asm_c.c:104]: I haven't checked IAR and would really appreciate it if you could try it out!

**Review by DGA45 — APPROVED** [review]
Tested OK on keil uVision ARM Compiler v6.22 with option -Oz

**Review by dgarske — APPROVED** [review]
IAR ARM 9.50.1 is happy with the new syntax.
