### PR TITLE
Minor wolfCrypt Test Fixes

### LINKED ISSUE #2920: Invalid use of sizeof() on pointers in Ed448 tests
When building with clang and `-Werror` (and the default of `--enable-crypttests`) I get the following errors:

```
wolfcrypt/test/test.c:23114:42: error: 'XMEMCMP' call operates on objects of type 'const byte' (aka 'const unsigned char') while the size is based on a different type 'const byte *' (aka 'const unsigned char *') [-Werror,-Wsizeof-pointer-memaccess]
        if (XMEMCMP(out, sigs[i], sizeof(sigs[i])))
                         ~~~~~~~         ^~~~~~~
wolfcrypt/test/test.c:23114:42: note: did you mean to provide an explicit length?
        if (XMEMCMP(out, sigs[i], sizeof(sigs[i])))
                                         ^~~~~~~
wolfcrypt/test/test.c:23146:38: error: 'XMEMCMP' call operates on objects of type 'const byte' (aka 'const unsigned char') while the size is based on a different type 'const byte *' (aka 'const unsigned char *') [-Werror,-Wsizeof-pointer-memaccess]
    if (XMEMCMP(out, sigs[0], sizeof(sigs[0])))
                     ~~~~~~~         ^~~~~~~
wolfcrypt/test/test.c:23146:38: note: did you mean to provide an explicit length?
    if (XMEMCMP(out, sigs[0], sizeof(sigs[0])))
                                     ^~~~~~~
wolfcrypt/test/test.c:23167:38: error: 'XMEMCMP' call operates on objects of type 'const byte' (aka 'const unsigned char') while the size is based on a different type 'const byte *' (aka 'const unsigned char *') [-Werror,-Wsizeof-pointer-memaccess]
    if (XMEMCMP(out, sigs[0], sizeof(sigs[0])))
                     ~~~~~~~         ^~~~~~~
wolfcrypt/test/test.c:23167:38: note: did you mean to provide an explicit length?
    if (XMEMCMP(out, sigs[0], sizeof(sigs[0])))
                                     ^~~~~~~
3 errors generated.
```

These are from the newly added Ed448 test cases.  Using a pointer to an array in `sizeof()` and not the array itself  causes these checks to only compare the first 8 bytes (on x64) of the signatures.

### PR DESCRIPTION
**Pull request by ejohnstown**
Fix a couple of wolfCrypt test issues found during the long release build test.

Fixes #2920

### CODE REVIEW

File: wolfcrypt/test/test.c [hunk 1]
```diff
@@ -22833,6 +22834,7 @@ int ed448_test(void)
     };
 
     static const byte* sigs[] = {sig1, sig2, sig3, sig4, sig5, sig6};
+    #define SIGSZ sizeof(sig1)
```
Comment (dgarske) [inline wolfcrypt/test/test.c:22837]: There is another one like this in `ed25519_test`.  Out of curiosity what's wrong with the `sizeof(sigs[i]` used previously?

Comment (ejohnstown) [reply wolfcrypt/test/test.c:22837]: sigs[] is an array of const char pointers. That sizeof is 8, not the desired 114.

Comment (ejohnstown) [reply wolfcrypt/test/test.c:22837]: In ed25519_test, they didn't use sizeof() for the length of the signature values. All the XMEMCMP()s are using a hardcoded length of 64.
