### PR TITLE
Fix broken verify on Ada wrapper

### LINKED ISSUE #7461: Ada wrapper incorrectly sets verification method for remote peers
I think there is a bug in the logic for setting the verification method in the Ada wrapper [here](https://github.com/wolfSSL/wolfssl/blob/c3d9fb61a88322eaaa237545e1027e05ac6c6d2f/wrapper/Ada/wolfssl.ads#L103).

The documentation suggests it should be a logical OR operator [here](https://github.com/wolfSSL/wolfssl/blob/master/wrapper/Ada/wolfssl.adb#L174).

However, it performs an AND operator [here](https://github.com/wolfSSL/wolfssl/blob/master/wrapper/Ada/wolfssl.adb#L211).

Unless the documentation is incorrect! But the C examples suggest it is a logical OR [here](https://github.com/wolfSSL/wolfssl-examples/blob/master/tls/server-tls13.c#L220).

### PR DESCRIPTION
**Pull request by LinuxJedi**
# Description

The Ada wrapper had an `&` operator for the verification mode. This effectively caused the verification mode to equal `0`.

The operator has been switched to `or` now, in addition, a getter has been added to the API. This allows for the test I've added to the server code to verify that it is being set correctly.

`OPENSSL_ALL` flag added to Ada so that the verify mode getter function is compiled in.

Fixes #7461

Thanks to @dalybrown for reporting it.

# Testing

Test added to the `tls_server_main` code, it will abort with an error if the mode is not set correctly. Also confirmed by inspecting the parameters given to `wolfSSL_CTX_set_verify()` and `wolfSSL_CTX_get_verify()` when they were called.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Review by dgarske — APPROVED** [review]

**Comment by dgarske** [comment]
Will @joakim-strandberg and @dalybrown please review also? Thank you

File: wrapper/Ada/user_settings.h [hunk 1]
```diff
@@ -260,10 +260,10 @@ extern "C" {
 
 
 /* Openssl compatibility */
+#define OPENSSL_ALL
```
Comment (dgarske) [inline wrapper/Ada/user_settings.h:263]: Not a fan of having to enable and pull in 100% of the compatibility layer. Once https://github.com/wolfSSL/wolfssl/pull/8258 is merged just use OPENSSL_EXTRA.
Unless you can find a way to avoid it.

Comment (LinuxJedi) [reply wrapper/Ada/user_settings.h:263]: I wasn't a fan of it either, but couldn't see another way without removing the guard on that function or completely re-implementing it in the Ada C wrapper. I'll update this with OPENSSL_EXTRA today.

**Review by dgarske — APPROVED** [review]
