### PR TITLE
server: allow reading 0-RTT data after writing 0.5-RTT data

### LINKED ISSUE #7093: [Bug]: SSL_read_early_data returns OUT_OF_ORDER_E after SSL_write
### Contact Details

_No response_

### Version

5.6.6

### Description

./configure --enable-all --enable-quic --enable-aesni --enable-harden --enable-debug
linux amd64

### Reproduction steps

My server reads TLSv1.3 early data with SSL_read_early_data (I use OpenSSL compatible header to port my server from OpenSSL to wolfSSL).
If I understand TLSv1.3 early data correctly, server can send messages including application data without reading all early data.
This works for other TLS stacks, like OpenSSL and BoringSSL.  SSL_write is used for this purpose, and this works fine and client gets this data.  The problem is , after SSL_write, SSL_read_early_data returns OUT_OF_ORDER_E, and sends TLS alert, and connection is gone.

While I was poking around wolfSSL source code, I found that wolfSSL_write resets ssl->earlyData to no_early_data:
https://github.com/wolfSSL/wolfssl/blob/daf1d1728f8022d99464abb6c2917492345b24eb/src/ssl.c#L3255

This makes SSL_read_early_data misbehaving because  early data is suddenly disabled.
This line is probably there for some purpose, but it prevents sending application data before reading all early data from client.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by julek-wolfssl**

### CODE REVIEW

File: src/internal.c [hunk 1]
```diff
@@ -24243,7 +24247,7 @@ int ReceiveData(WOLFSSL* ssl, byte* output, int sz, int peek)
     }
 
 #ifdef WOLFSSL_EARLY_DATA
-    if (ssl->earlyData != no_early_data) {
+    if (ssl->earlyData > early_data_ext && ssl->earlyData < done_early_data) {
```
Comment (SparkiDev) [inline src/internal.c:24250]: Can you put side check here too?

**Review by SparkiDev — CHANGES_REQUESTED** [review]

File: src/internal.c (hunk 1 above)
Comment (julek-wolfssl) [reply src/internal.c]: Added side check.

**Review by SparkiDev — APPROVED** [review]
