### PR TITLE
Fix cppcheck

### LINKED ISSUE #2570: cppcheck findings
```
[IDE/IAR-EWARM/Projects/common/minimum-startup.c:42]: (error) syntax error: ".intvec" =
[IDE/LPCXPRESSO/wolf_example/src/lpc_18xx_startup.c:31] -> [IDE/LPCXPRESSO/wolf_example/src/lpc_18xx_startup.c:87] -> [IDE/LPCXPRESSO/wolf_example/src/lpc_18xx_startup.c:32] -> [IDE/LPCXPRESSO/wolf_example/src/lpc_18xx_startup.c:89] -> [IDE/LPCXPRESSO/wolf_example/src/lpc_18xx_startup.c:89]: (error) Comparing pointers that point to different objects
[IDE/zephyr/lib/user_settings.h:8]: (error) No header in #include
[src/internal.c:27338]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
[wolfcrypt/src/fe_operations.c:159]: (error) Uninitialized variable: x1
[wolfcrypt/src/fe_operations.c:160]: (error) Uninitialized variable: x2
[wolfcrypt/src/fe_operations.c:161]: (error) Uninitialized variable: z2
[wolfcrypt/src/fe_operations.c:162]: (error) Uninitialized variable: x3
[wolfcrypt/src/fe_operations.c:163]: (error) Uninitialized variable: z3
[wolfcrypt/src/fe_operations.c:196]: (error) Uninitialized variable: tmp0
[wolfcrypt/src/fe_operations.c:196]: (error) Uninitialized variable: tmp1
[wolfcrypt/src/fe_operations.c:655]: (error) Uninitialized variable: t0
[wolfcrypt/src/fe_operations.c:656]: (error) Uninitialized variable: t1
[wolfcrypt/src/fe_operations.c:659]: (error) Uninitialized variable: t2
[wolfcrypt/src/fe_operations.c:665]: (error) Uninitialized variable: t3
[wolfcrypt/src/fe_operations.c:1271]: (error) Uninitialized variable: t0
[wolfcrypt/src/fe_operations.c:1272]: (error) Uninitialized variable: t1
[wolfcrypt/src/fe_operations.c:1281]: (error) Uninitialized variable: t2
[wolfcrypt/src/integer.c:2324]: (error) Uninitialized variable: redux
[wolfcrypt/src/integer.c:2352]: (error) Uninitialized variable: redux
[wolfcrypt/src/pkcs7.c:2638]: (error) Address of local auto-variable assigned to a function parameter.
[wolfcrypt/src/pkcs7.c:2750]: (error) Address of local auto-variable assigned to a function parameter.
[wolfcrypt/src/pkcs7.c:2851]: (error) Address of local auto-variable assigned to a function parameter.
[wolfcrypt/src/pkcs7.c:2990]: (error) Address of local auto-variable assigned to a function parameter.
[wolfcrypt/src/sp_arm32.c:22639]: (error) Shifting by a negative value is undefined behaviour
[wolfcrypt/src/sp_armthumb.c:12961]: (error) Shifting by a negative value is undefined behaviour
[wolfcrypt/src/sp_cortexm.c:13148]: (error) Shifting by a negative value is undefined behaviour
[wolfcrypt/src/wc_port.c:1313]: (error) Uninitialized variable: p
[wolfcrypt/src/wc_port.c:1407]: (error) Uninitialized variable: p
```

```
[IDE/Espressif/ESP-IDF/test/test_wolfssl.c:283]: (warning) %llu in format string (no. 1) requires 'unsigned long long' but the argument type is 'unsigned long'.
[IDE/Espressif/ESP-IDF/test/test_wolfssl.c:286]: (warning) %llu in format string (no. 1) requires 'unsigned long long' but the argument type is 'unsigned long'.
[IDE/Espressif/ESP-IDF/test/test_wolfssl.c:289]: (warning) %llu in format string (no. 1) requires 'unsigned long long' but the argument type is 'unsigned long'.
[IDE/GCC-ARM/Source/armtarget.c:145]: (warning) %lx in format string (no. 1) requires 'unsigned long' but the argument type is 'unsigned int'.
[IDE/GCC-ARM/Source/armtarget.c:146]: (warning) %lx in format string (no. 1) requires 'unsigned long' but the argument type is 'unsigned int'.
[IDE/GCC-ARM/Source/armtarget.c:147]: (warning) %lx in format string (no. 1) requires 'unsigned long' but the argument type is 'unsigned int'.
[IDE/GCC-ARM/Source/armtarget.c:148]: (warning) %lx in format string (no. 1) requires 'unsigned long' but the argument type is 'unsigned int'.
[IDE/GCC-ARM/Source/armtarget.c:149]: (warning) %lx in format string (no. 1) requires 'unsigned long' but the argument type is 'unsigned int'.
[IDE/GCC-ARM/Source/armtarget.c:150]: (warning) %lx in format string (no. 1) requires 'unsigned long' but the argument type is 'unsigned int'.
[IDE/GCC-ARM/Source/armtarget.c:151]: (warning) %lx in format string (no. 1) requires 'unsigned long' but the argument type is 'unsigned int'.
[IDE/GCC-ARM/Source/armtarget.c:152]: (warning) %lx in format string (no. 1) requires 'unsigned long' but the argument type is 'unsigned int'.
[IDE/GCC-ARM/Source/armtarget.c:153]: (warning) %lx in format string (no. 1) requires 'unsigned long' but the argument type is 'unsigned int'.
[IDE/GCC-ARM/Source/armtarget.c:154]: (warning) %lx in format string (no. 1) requires 'unsigned long' but the argument type is 'unsigned int'.
[IDE/GCC-ARM/Source/armtarget.c:155]: (warning) %lx in format string (no. 1) requires 'unsigned long' but the argument type is 'unsigned int'.
[IDE/GCC-ARM/Source/armtarget.c:156]: (warning) %lx in format string (no. 1) requires 'unsigned long' but the argument type is 'unsigned int'.
[IDE/GCC-ARM/Source/armtarget.c:157]: (warning) %lx in format string (no. 1) requires 'unsigned long' but the argument type is 'unsigned int'.
[IDE/GCC-ARM/Source/armtarget.c:158]: (warning) %lx in format string (no. 1) requires 'unsigned long' but the argument type is 'unsigned int'.
[IDE/IAR-EWARM/Projects/benchmark/current_time.c:47]: (warning) %d in format string (no. 1) requires 'int' but the argument type is 'unsigned int'.
[IDE/MDK-ARM/MDK-ARM/wolfSSL/shell.c:439] -> [IDE/MDK-ARM/MDK-ARM/wolfSSL/shell.c:440]: (warning) Either the condition 'args==NULL' is redundant or there is possible null pointer dereference: args.
[IDE/MDK-ARM/MDK-ARM/wolfSSL/wolfssl_MDK_ARM.c:72]: (warning) %d in format string (no. 1) requires 'int *' but the argument type is 'unsigned int *'.
[IDE/MDK-ARM/MDK-ARM/wolfSSL/wolfssl_MDK_ARM.c:72]: (warning) %d in format string (no. 2) requires 'int *' but the argument type is 'unsigned int *'.
[IDE/MDK-ARM/MDK-ARM/wolfSSL/wolfssl_MDK_ARM.c:72]: (warning) %d in format string (no. 3) requires 'int *' but the argument type is 'unsigned int *'.
[IDE/MDK-ARM/MDK-ARM/wolfSSL/wolfssl_MDK_ARM.c:72]: (warning) %d in format string (no. 4) requires 'int *' but the argument type is 'unsigned int *'.
[IDE/MDK5-ARM/Projects/wolfSSL-Full/shell.c:480] -> [IDE/MDK5-ARM/Projects/wolfSSL-Full/shell.c:481]: (warning) Either the condition 'args==NULL' is redundant or there is possible null pointer dereference: args.
[IDE/RISCV/SIFIVE-HIFIVE1/main.c:146]: (warning) %d in format string (no. 1) requires 'int' but the argument type is 'unsigned long'.
[IDE/RISCV/SIFIVE-HIFIVE1/main.c:151]: (warning) %d in format string (no. 1) requires 'int' but the argument type is 'signed long'.
[examples/benchmark/tls_bench.c:1282] -> [examples/benchmark/tls_bench.c:1258]: (warning) Either the condition 'if(args)' is redundant or there is possible null pointer dereference: args.
[examples/benchmark/tls_bench.c:1282] -> [examples/benchmark/tls_bench.c:1259]: (warning) Either the condition 'if(args)' is redundant or there is possible null pointer dereference: args.
[examples/client/client.c:318]: (warning) Assignment of function parameter has no effect outside the function. Did you forget dereferencing it?
[examples/client/client.c:319]: (warning) Assignment of function parameter has no effect outside the function. Did you forget dereferencing it?
[examples/server/server.c:997] -> [examples/server/server.c:1000] -> [examples/server/server.c:1961] -> [examples/server/server.c:1962]: (warning) Opposite inner 'if' condition leads to a dead code block.
[examples/server/server.c:888] -> [examples/server/server.c:889] -> [examples/server/server.c:1608]: (warning) Logical disjunction always evaluates to true: !(usePsk) || usePskPlus.
[examples/server/server.c:888] -> [examples/server/server.c:889] -> [examples/server/server.c:1649]: (warning) Logical disjunction always evaluates to true: !(usePsk) || usePskPlus.
[examples/server/server.c:1726]: (warning) Logical disjunction always evaluates to true: usePsk == 0 || usePskPlus.
[examples/server/server.c:888] -> [examples/server/server.c:889] -> [examples/server/server.c:1842]: (warning) Logical disjunction always evaluates to true: !(usePsk) || usePskPlus.
[examples/server/server.c:1842]: (warning) Logical conjunction always evaluates to false: !useAnon && loadCertKeyIntoSSLObj.
[examples/server/server.c:888] -> [examples/server/server.c:889] -> [examples/server/server.c:1854]: (warning) Logical disjunction always evaluates to true: !(usePsk) || usePskPlus.
[examples/server/server.c:1854]: (warning) Logical conjunction always evaluates to false: !useAnon && loadCertKeyIntoSSLObj.
[examples/server/server.c:2072]: (warning) Logical disjunction always evaluates to true: usePsk == 0 || usePskPlus.
[mcapi/mcapi_test.c:103]: (warning) Redundant code: Found a statement that begins with numeric constant.
[mqx/wolfssl_client/Sources/main.c:150]: (warning) %d in format string (no. 1) requires 'int' but the argument type is 'unsigned int'.
[mqx/wolfssl_client/Sources/main.c:150]: (warning) %d in format string (no. 2) requires 'int' but the argument type is 'unsigned int'.
[src/bio.c:459] -> [src/bio.c:539]: (warning) Either the condition 'bio' is redundant or there is possible null pointer dereference: bio.
[src/internal.c:10246] -> [src/internal.c:10263]: (warning) Identical inner 'if' condition is always true.
[src/internal.c:14064] -> [src/internal.c:14104]: (warning) Variable 'ssl->options.processReply' is reassigned a value before the old one has been used. 'break;' missing?
[src/internal.c:15049] -> [src/internal.c:15041]: (warning) Either the condition 'ssl==NULL' is redundant or there is possible null pointer dereference: ssl.
[src/internal.c:25739] -> [src/internal.c:25822]: (warning) Variable 'ssl->options.asyncState' is reassigned a value before the old one has been used. 'break;' missing?
[src/ssl.c:5227] -> [src/ssl.c:5216]: (warning) Either the condition 'if(ctx)' is redundant or there is possible null pointer dereference: ctx.
[src/ssl.c:28125]: (warning) Assignment of function parameter has no effect outside the function. Did you forget dereferencing it?
[src/ssl.c:30796]: (warning) Assignment of function parameter has no effect outside the function. Did you forget dereferencing it?
[src/ssl.c:31081]: (warning) Assignment of function parameter has no effect outside the function. Did you forget dereferencing it?
[src/ssl.c:31482]: (warning) Assignment of function parameter has no effect outside the function. Did you forget dereferencing it?
[src/ssl.c:43069]: (warning) Assignment of function parameter has no effect outside the function. Did you forget dereferencing it?
[src/ssl.c:43124]: (warning) Assignment of function parameter has no effect outside the function. Did you forget dereferencing it?
[src/ssl.c:5286] -> [src/ssl.c:5273]: (warning) Either the condition 'if(ctx)' is redundant or there is possible null pointer dereference: ctx.
[src/ssl.c:18581] -> [src/ssl.c:18582]: (warning) Opposite inner 'if' condition leads to a dead code block.
[src/ssl.c:37861] -> [src/ssl.c:37831]: (warning) Either the condition 'key!=NULL' is redundant or there is possible null pointer dereference: key.
[src/tls.c:5566] -> [src/tls.c:5561]: (warning) Either the condition 'extensions==NULL' is redundant or there is possible null pointer dereference: extensions.
[tests/api.c:16194] -> [tests/api.c:16195]: (warning) Identical inner 'if' condition is always true.
[tests/api.c:2183] -> [tests/api.c:2236]: (warning) Either the condition 'args' is redundant or there is possible null pointer dereference: args.
[wolfcrypt/src/asn.c:9403] -> [wolfcrypt/src/asn.c:9324]: (warning) Either the condition 'if(pBuffer)' is redundant or there is possible null pointer dereference: pBuffer.
[wolfcrypt/src/asn.c:10786] -> [wolfcrypt/src/asn.c:10790]: (warning) Identical condition 'output==NULL', second condition is always false
[wolfcrypt/src/dh.c:1634] -> [wolfcrypt/src/dh.c:1637]: (warning) Identical inner 'if' condition is always true.
[wolfcrypt/src/ecc.c:5223] -> [wolfcrypt/src/ecc.c:5234]: (warning) Identical inner 'if' condition is always true.
[wolfcrypt/src/ecc.c:8658] -> [wolfcrypt/src/ecc.c:8659]: (warning) Identical inner 'if' condition is always true.
[wolfcrypt/src/memory.c:1045]: (warning) %d in format string (no. 6) requires 'int' but the argument type is 'unsigned int'.
[wolfcrypt/src/memory.c:1075]: (warning) %d in format string (no. 6) requires 'int' but the argument type is 'unsigned int'.
[wolfcrypt/src/memory.c:1078]: (warning) %d in format string (no. 6) requires 'int' but the argument type is 'unsigned int'.
[wolfcrypt/src/memory.c:1095]: (warning) %d in format string (no. 6) requires 'int' but the argument type is 'unsigned int'.
[wolfcrypt/src/pkcs7.c:4074] -> [wolfcrypt/src/pkcs7.c:4079]: (warning) Identical condition 'pkcs7==NULL', second condition is always false
[wolfcrypt/src/pkcs7.c:2447] -> [wolfcrypt/src/pkcs7.c:2440]: (warning) Either the condition 'if(output2&&output2Sz)' is redundant or there is pointer arithmetic with NULL pointer.
[wolfcrypt/src/pkcs7.c:2447] -> [wolfcrypt/src/pkcs7.c:2442]: (warning) Either the condition 'if(output2&&output2Sz)' is redundant or there is pointer arithmetic with NULL pointer.
[wolfcrypt/src/pkcs7.c:2447] -> [wolfcrypt/src/pkcs7.c:2444]: (warning) Either the condition 'if(output2&&output2Sz)' is redundant or there is pointer arithmetic with NULL pointer.
[wolfcrypt/src/pkcs7.c:10004] -> [wolfcrypt/src/pkcs7.c:10042]: (warning) Variable 'tmpIdx' is reassigned a value before the old one has been used. 'break;' missing?
[wolfcrypt/src/pkcs7.c:10400] -> [wolfcrypt/src/pkcs7.c:10404]: (warning) Identical condition 'blockKeySz<0', second condition is always false
[wolfcrypt/src/pkcs7.c:10868] -> [wolfcrypt/src/pkcs7.c:10922]: (warning) Variable 'tmpIdx' is reassigned a value before the old one has been used. 'break;' missing?
[wolfcrypt/src/pkcs7.c:8384] -> [wolfcrypt/src/pkcs7.c:8382]: (warning) Either the condition 'idx==NULL' is redundant or there is possible null pointer dereference: idx.
[wolfcrypt/src/port/intel/quickassist_sync.c:514]: (warning) %u in format string (no. 1) requires 'unsigned int' but the argument type is 'signed int'.
[wolfcrypt/src/port/intel/quickassist_sync.c:1535]: (warning) %d in format string (no. 4) requires 'int' but the argument type is 'unsigned int'.
[wolfcrypt/src/port/intel/quickassist_sync.c:1683]: (warning) %d in format string (no. 4) requires 'int' but the argument type is 'unsigned int'.
[wolfcrypt/src/port/intel/quickassist_sync.c:1844]: (warning) %d in format string (no. 5) requires 'int' but the argument type is 'unsigned int'.
[wolfcrypt/src/port/intel/quickassist_sync.c:1848]: (warning) %d in format string (no. 4) requires 'int' but the argument type is 'unsigned int'.
[wolfcrypt/src/random.c:466] -> [wolfcrypt/src/random.c:489]: (warning) Opposite inner 'if' condition leads to a dead code block.
[wolfcrypt/src/random.c:2349] -> [wolfcrypt/src/random.c:2376]: (warning) Either the condition 'os!=NULL' is redundant or there is possible null pointer dereference: os.
[wolfcrypt/src/random.c:2349] -> [wolfcrypt/src/random.c:2377]: (warning) Either the condition 'os!=NULL' is redundant or there is possible null pointer dereference: os.
[wolfcrypt/src/rsa.c:1983] -> [wolfcrypt/src/rsa.c:2010]: (warning) Identical inner 'if' condition is always true.
[wolfcrypt/src/rsa.c:1983] -> [wolfcrypt/src/rsa.c:2028]: (warning) Identical inner 'if' condition is always true.
[wolfcrypt/src/rsa.c:2010] -> [wolfcrypt/src/rsa.c:2028]: (warning) Identical inner 'if' condition is always true.
[wolfcrypt/src/sp_int.c:1759] -> [wolfcrypt/src/sp_int.c:1846]: (warning) Either the condition 'result==NULL' is redundant or there is possible null pointer dereference: result.
[wolfcrypt/test/test.c:5251] -> [wolfcrypt/test/test.c:5259]: (warning) Identical condition 'err', second condition is always false
[wolfcrypt/user-crypto/src/rsa.c:1623]: (warning) Assignment of function parameter has no effect outside the function. Did you forget dereferencing it?
[wolfcrypt/user-crypto/src/rsa.c:696] -> [wolfcrypt/user-crypto/src/rsa.c:695]: (warning) Either the condition 'mont==NULL' is redundant or there is possible null pointer dereference: mont.
[src/bio.c:529] -> [src/bio.c:533] -> [src/bio.c:311]: (warning) Null pointer dereference: bio
```

```
[wolfcrypt/src/sp_c32.c:1305]: (style) Condition '!r' is always true
[wolfcrypt/src/sp_c32.c:2189]: (style) Condition '!r' is always true
[wolfcrypt/src/sp_c32.c:4848]: (style) Condition '!r' is always true
[wolfcrypt/src/sp_c32.c:5691]: (style) Condition '!r' is always true
[wolfcrypt/src/sp_c32.c:8156]: (style) Condition '!r' is always true
[wolfcrypt/src/sp_c64.c:945]: (style) Condition '!r' is always true
[wolfcrypt/src/sp_c64.c:1793]: (style) Condition '!r' is always true
[wolfcrypt/src/sp_c64.c:4760]: (style) Condition '!r' is always true
[wolfcrypt/src/sp_c64.c:5594]: (style) Condition '!r' is always true
[wolfcrypt/src/sp_c64.c:7847]: (style) Condition '!r' is always true
[wolfcrypt/src/tfm.c:2826]: (style) Condition 'cy' is always false
[wolfcrypt/src/wc_pkcs11.c:855] -> [wolfcrypt/src/wc_pkcs11.c:872]: (style) The expression 'ret == 0' is always true.
[wolfcrypt/src/wc_pkcs11.c:935] -> [wolfcrypt/src/wc_pkcs11.c:944]: (style) The expression 'ret == 0' is always true.
[wolfcrypt/test/test.c:14493]: (style) Condition 'openssl_aes_test()!=0' is always false
[wolfcrypt/test/test.c:24204] -> [wolfcrypt/test/test.c:24289]: (style) The expression 'ret >= 0' is always true.

```

### PR DESCRIPTION
**Pull request by tmael**
This PR fixes errors and warnings found with cppcheck.

$ cd ~/wolfssl
$ cppcheck --force --enable=all . 2>&1 | tee cppcheck.enable-all.txt
$ grep error cppcheck.enable-all.txt
$ grep warning cppcheck.enable-all.txt

Fixes #2570

### CODE REVIEW

File: tests/api.c [hunk 1]
```diff
@@ -2258,7 +2258,7 @@ static THREAD_RETURN WOLFSSL_THREAD test_server_nofail(void* args)
 
 #ifdef WOLFSSL_SESSION_EXPORT
     /* only add in more complex nonblocking case with session export tests */
-    if (args && ((func_args*)args)->argc > 0) {
+    if (((func_args*)args)->argc > 0) {
```
Comment (JacobBarthelmeh) [inline tests/api.c]: does this introduce a case where a null dereference of args is possible?

File: src/ssl.c [hunk 2]
```diff
@@ -19317,7 +19317,6 @@ void wolfSSL_ACCESS_DESCRIPTION_free(WOLFSSL_ACCESS_DESCRIPTION* access)
         wolfSSL_ASN1_OBJECT_free(access->method);
     if (access->location)
         wolfSSL_GENERAL_NAME_free(access->location);
-    access = NULL;
```
Comment (JacobBarthelmeh) [inline src/ssl.c]: In these cases is better to keep the code to set the pointer to NULL to make sure that any future code does not double free or try accessing an address that has already been free'd

File: tests/api.c (hunk 1 above)
Comment (tmael) [reply tests/api.c]: @JacobBarthelmeh, I don't think so. null deference of args would cause issues early one.  For example, at the beginning of the function at
  ((func_args*)args)->return_code = TEST_FAIL;

**Comment by kaleb-himes** [comment]
retest this please
