### PR TITLE
Fix RNG with writedup

### LINKED ISSUE #6760: [Bug]: Memory leak in ssl->rng
### Contact Details

razvan@opensips.org

### Version

5.4.0

### Description

We are compiling the library static, as it follows:
```
 ./configure \
	--enable-all --disable-fpecc -disable-aligndata --disable-examples \
	--enable-writedup --enable-tlsv10 --disable-shared --enable-static \
	--disable-jni --disable-crl-monitor \
	C_EXTRA_FLAGS="-fPIC" \
	CFLAGS="-DWOLFSSL_STATIC_RSA -DWOLFSSL_DEBUG_MEMORY"
```
We are using our own memory allocators, which are keeping track of the memory usage, and we have identified a memory leak of the `ssl->rng` memory allocated in [InitSSL](https://github.com/wolfSSL/wolfssl/blob/v5.4.0-stable/src/internal.c#L6723)  function, along with an equal number of chunks allocated from [_InitRng](https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/random.c#L1633). The number of fragments/chunks allocated in these two places are 100x more than the number of actual `WOLFSSL ssl` contexts, and they are never going down - this confirms 100% this is a leak.

We have tried to troubleshoot this ourselves, and observed that the release of the `ssl->rng` structure [depends](https://github.com/wolfSSL/wolfssl/blob/v5.4.0-stable/src/internal.c#L7574) on the `ssl->options.weOwnRng` field, which is properly set to `1` when the memory is [allocated](https://github.com/wolfSSL/wolfssl/blob/v5.4.0-stable/src/internal.c#L6729). However, when the memory is released, its value is `0` - this is acutally the bug; We have checked the code and the weOwnRng is only reset in [one](https://github.com/wolfSSL/wolfssl/blob/v5.4.0-stable/src/internal.c#L7574) place, when `ssl->rng` is also set to `NULL`. However, according to our logs, when `FreeSSL` and `SSL_ResourceFree` functions are called, our `ssl->options.weOwnRng` is set `0`, but `ssl->rng` is present as well (not `NULL`). We're also not using `SINGLE_THREADED`, thus we have our own rng (which we've seen allocated in our memory logs).

Bottom line, we do not understand who overwrites the `weOwnRng` field without resetting or freeing the `ssl->rng` structure. I was suspecting this as a compiler issue (related to bitfield usage of `weOwnRng`), but I am not sure how to prove (and hopefully fix) it.

In the meantime, we have changed [this](https://github.com/wolfSSL/wolfssl/blob/v5.4.0-stable/src/internal.c#L7210) code as it follows:
```
-    if (ssl->options.weOwnRng) {
+    if (ssl->options.weOwnRng || (ssl->rng
+#ifdef SINGLE_THREADED
+        && ssl->rng != ssl->ctx->rng
+#endif
+       )) {
```
This fixes our leak, but I don't think is the correct approach, as I still don't understand how `weOwnRng` gets changed. Any help would be really appreciated.

### Reproduction steps

 ```
 ./configure \
	--enable-all --disable-fpecc -disable-aligndata --disable-examples \
	--enable-writedup --enable-tlsv10 --disable-shared --enable-static \
	--disable-jni --disable-crl-monitor \
	C_EXTRA_FLAGS="-fPIC" \
	CFLAGS="-DWOLFSSL_STATIC_RSA -DWOLFSSL_DEBUG_MEMORY"
```

Run a few hundreds connections. Run a memory dump and check the logs - they will show a huge number of `ssl->rng` and `ssl->rng->drbg` chunks unalocated. Check the logs below. Note that not all of the fragments get leaked, only some of them.

### Relevant log output

```shell
BAD:
  169585| 2023-09-07 15:33:30.452|       src/internal.c   6763: ctx=0x7f3240d335c8 ssl=0x7f3243b974e0 rng=0x7f3243bcf408 weOwnRng=1 v=TLSv1: allocated
  169588| 2023-09-07 15:33:33.536|       src/internal.c   7776: ctx=0x7f3240d335c8 ssl=0x7f3243b974e0 rng=0x7f3243bcf408 weOwnRng=0 v=TLSv1: releasing
  169588| 2023-09-07 15:33:33.536|       src/internal.c   7233: ctx=0x7f3240d335c8 ssl=0x7f3243b974e0 rng=0x7f3243bcf408 weOwnRng=0 v=TLSv1: freeing forcefully


GOOD:
  169578| 2023-09-07 15:03:48.641|       src/internal.c   6763: ctx=0x7f3240d335c8 ssl=0x7f32432334c0 rng=0x7f32473e8380 own=1 v=TLSv1: allocated                                                  
  169588| 2023-09-07 15:04:12.422|       src/internal.c   7776: ctx=0x7f3240d335c8 ssl=0x7f32432334c0 rng=0x7f32473e8380 own=1 v=TLSv1: releasing                                                  
  169588| 2023-09-07 15:04:12.422|       src/internal.c   7235: ctx=0x7f3240d335c8 ssl=0x7f32432334c0 rng=0x7f32473e8380 own=1 v=TLSv1: freeing OK
```

### PR DESCRIPTION
**Pull request by embhorn**
# Description

Fixes RNG management when using writedup
This corrects a problem from #6785 with TLS1.2 connections having the writedup SSL deallocate the RNG.

Fixes #6760 

# Testing

## wolfSSL
`./configure --enable-all --enable-debug --enable-writedup`

## wolfssl-examples

Run `wolfssl-examples/tls$ ./server-tls-writedup`
and `wolfssl-examples/tls$ ./client-tls-writedup 127.0.0.1`

Observe failures when writing message in client (after handshake).

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

File: src/ssl.c [hunk 1]
```diff
@@ -1595,6 +1592,9 @@ static int DupSSL(WOLFSSL* dup, WOLFSSL* ssl)
     dup->truncated_hmac = ssl->truncated_hmac;
 #endif
 
+    /* Restore rng option */
+    dup->options.weOwnRng = tmp_weOwnRng;
```
Comment (dgarske) [inline src/ssl.c:1596]: This is not the right fix. After the memcpy of the options it should forcefully set the `dup->rng = NULL` and the `dup->options.weOwnRng = 0;` not touching anything else. We can't share the ownership of the RNG.

**Review by dgarske — CHANGES_REQUESTED** [review]

File: src/ssl.c (hunk 1 above)
Comment (embhorn) [reply src/ssl.c:1596]: The structures for `dup` and `ssl` are both initialized, and the each have their own RNG. This fix preserves the `weOwnRng` value, so that each one can be freed during `wolfSSL_free`. There is no sharing of the RNG.

**Review by dgarske — APPROVED** [review]

**Review by JacobBarthelmeh — APPROVED** [review]
