### PR TITLE
hostap update

### LINKED ISSUE #7391: [Bug, openSSL compatibility]:
### Contact Details

my first name is laurenz. E-Mail [firstname].grote@rwth-aachen.de

### Version

reproduced in current HEAD c768f76d5a72e77507241c7b7d0666a846a0d63

### Description

Hello!

First and foremost thank you for the support provided so far. I am writing about an inconsistency with OpenSSL. In Wolf the function `wolfSSL_CTX_set1_groups_list` only accepts NIST curves (e.g. prime256) , but not Bernstein curves such as  `X25519`. This is because `populate_groups` in `ssl.c` refers to the dictionary `kNistCurves` in the same file, which lacks the Bernstein curves.
The analogous function `SSL_CTX_set1_groups_list` in OpenSSL accepts X25519, as also listed in their documentation: https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set1_groups_list.html`

I would suggest to extend the dicitionary by the Non-NIST Curves such that `wolfSSL_CTX_set1_groups_list` a) is compatible to OpenSSL and b) `wolfSSL_CTX_set1_groups_list` can supersede `wolfSSL_CTX_set1_curves_list`.

My configuration is:

./autogen.sh && ./configure --with-liboqs=/liboqs --enable-nullcipher --enable-psk --enable-opensslextra --enable-debug --enable-tls13 --enable-ecccustcurves  --enable-brainpool --enable-curve25519 --enable-ed25519 --enable-curve448 --enable-ed448 CFLAGS="-DWOLFSSL_STATIC_RSA -DWOLFSSL_STATIC_DH -DKEEP_PEER_CERT -DHAVE_SECRET_CALLBACK -DHAVE_SUPPORTED_CURVES"

Many Thanks

Cheers

Laurenz

### Reproduction steps

Apply 
`std::string name = "X25519"; wolfSSL_CTX_set1_curves_list(ctx, name.c_str())`. Works!

Apply
`std::string name = "X25519"; wolfSSL_CTX_set1_groups_list(ctx, name.c_str()))`. Error `Unrecognized curve name in list`!

But (in OpenSSL 3.1.1)
`std::string name = "X25519"; SSL_CTX_set1_groups_list(ctx, name.c_str()))`. Works!

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by julek-wolfssl**
- Implement PACs for EAP-FAST
  - wolfSSL_set_session_ticket_ext_cb
  - server side wolfSSL_set_session_secret_cb (tls <=1.2 only)
- Filter cipher list on TLS version change
- Remove unused internal API
- Advertise all supported sigalgs by default
- Expose *_set_groups for TLS < 1.3

### CODE REVIEW

**Comment by julek-wolfssl** [comment]
retest this please

File: wolfssl/internal.h [hunk 1]
```diff
@@ -2355,16 +2355,8 @@ typedef struct CipherSuite {
...
-                                         int haveRSAsig, int haveFalconSig,
-                                         int haveDilithiumSig, int haveAnon,
-                                         int tls1_2, int keySz);
-WOLFSSL_LOCAL void InitSuitesHashSigAlgo_ex(byte* hashSigAlgo, int haveECDSAsig,
-                                            int haveRSAsig, int haveFalconSig,
-                                            int haveDilithiumSig, int haveAnon,
-                                            int tls1_2, int keySz, word16* len);
 /* use wolfSSL_API visibility to be able to test in tests/api.c */
-WOLFSSL_API void InitSuitesHashSigAlgo_ex2(byte* hashSigAlgo, int have,
+WOLFSSL_API void InitSuitesHashSigAlgo(byte* hashSigAlgo, int have,
```
Comment (dgarske) [inline wolfssl/internal.h:2359]: This is marked as a public API. Should it be just to appease tests/api.c?

**Review by dgarske — CHANGES_REQUESTED** [review]

File: wolfssl/internal.h (hunk 1 above)
Comment (julek-wolfssl) [reply wolfssl/internal.h:2359]: Yes that is exactly why that is. We need a better way to mark that.

Comment (dgarske) [reply wolfssl/internal.h:2359]: I like this cleanup and I agree the api.c should be the only one using this API. It could come up as a red flag at release time, but let's take it.

**Review by dgarske — APPROVED** [review]
