### PR TITLE
Fix TLS 1.3 cipher suite when TLS 1.2 ciphers precede TLS 1.3 ciphers

### LINKED ISSUE #9030: [Bug]: Ssl_cipher list order matters on MariaDB linked against WolfSSL
### Contact Details

hartmut@mariadb.com

### Version

WolfSSL 5.7.6

### Description

With MariaDB linked against WolfSSL and specifying a list of accepted ciphers; TLS v1.3 clients can only connect when TLS v1.3 ciphers are listed first. Order does not matter when using OpenSSL instead.

Not sure whether that is an upstream or downstream problem after all, but as it works with OpenSSL it rather seems upstream, so I'm filing it here, too.

Related MariaDB bug report is: 

https://jira.mariadb.org/browse/MDEV-37307

### Reproduction steps

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by jackctj117**
# Description

Fixes TLS 1.3 handshake failure when TLS 1.2 cipher suites are listed before TLS 1.3 cipher suites in the server's cipher list. Modified VerifyServerSuite() to filter out TLS 1.2 ciphers during TLS 1.3 negotiation.
Fixes #9030

# Testing

Tested with example server/client using mixed cipher list:
./examples/server/server -v 4 -l ECDHE-RSA-AES128-GCM-SHA256:TLS13-AES128-GCM-SHA256
./examples/client/client -v 4
TLS 1.3 connection now succeeds regardless of cipher order.

### CODE REVIEW

File: src/internal.c [hunk 1]
```diff
@@ -37166,6 +37166,30 @@ static int DoSessionTicket(WOLFSSL* ssl, const byte* input, word32* inOutIdx,
...
+     * Returns 1 if TLS 1.3 cipher suite, 0 otherwise
+     */
+    static WC_INLINE int IsTls13CipherSuite(byte first, byte second)
+    {
+        /* TLS 1.3 cipher suites use TLS13_BYTE (0x13) as first byte */
+        if (first == TLS13_BYTE)
+            return 1;
+
+        /* Special cases for integrity-only cipher suites */
+        if (first == ECC_BYTE && (second == TLS_SHA256_SHA256 ||
```
Comment (SparkiDev) [inline src/internal.c:37183]: Add #ifdef protection like SuiteMac.

**Review by SparkiDev — CHANGES_REQUESTED** [review]

**Review by SparkiDev — DISMISSED** [review]

**Review by SparkiDev — DISMISSED** [review]

**Review by dgarske — APPROVED** [review]

**Review by dgarske — CHANGES_REQUESTED** [review]
Trailing whitespace. https://cloud.wolfssl-test.com/jenkins/job/PRB-multi-test-script/7872/pipeline-console/

**Review by dgarske — APPROVED** [review]

**Comment by dgarske** [comment]
Jenkins retest this please

**Comment by JacobBarthelmeh** [comment]
Retest this please Jenkins. FIPS rolling test error.

```
Cloning into 'wolfssl'...
fatal: couldn't find remote ref TLS13-cipher-suite-fix
```

**Review by JacobBarthelmeh — APPROVED** [review]
