### PR TITLE
d2i_ECPrivateKey() takes DER encoded data

### LINKED ISSUE #5064: [Bug]: d2i_ECPrivateKey() failure
### Contact Details

masashi.honma@gmail.com

### Version

e89b4cce4c5fcb42c76b46afd945352e3ec0863f

### Description

When using ```./configure --enable-all``` trailing program works fine. But when using ```./configure --enable-md4 --enable-des3 --enable-pwdbased --enable-wpas --enable-wpas-dpp 
--enable-opensslall --enable-opensslextra --enable-dsa --enable-keying-material --disable-tls13```, ```d2i_ECPrivateKey()``` returns ```NULL```. It seems this check causes failure.
```
int wc_ecc_set_curve(ecc_key* key, int keysize, int curve_id)
...
    if (keysize > ECC_MAXSIZE) {
        return ECC_BAD_ARG_E;
    }
...
```

This is the program extracted from hostapd/wpa_supplicant auto test.
```
#include <stdio.h>
#include <string.h>

#include <wolfssl/options.h>
#include <wolfssl/openssl/ec.h>
#include <wolfssl/openssl/evp.h>

int main(void)
{
	const unsigned char data[121] = {
		0x30, 0x77, 0x02, 0x01, 0x01, 0x04, 0x20, 0x02, 0x48, 0x1a, 0x57, 0xe7, 0xb5, 0xea, 0x27, 0x0d,
		0xbe, 0xeb, 0x43, 0x23, 0xff, 0x48, 0x64, 0x23, 0xc3, 0x3a, 0xd9, 0x02, 0x77, 0xeb, 0x5c, 0x89,
		0xb8, 0xdb, 0xcd, 0x15, 0x59, 0xa8, 0xd8, 0xa0, 0x0a, 0x06, 0x08, 0x2a, 0x86, 0x48, 0xce, 0x3d,
		0x03, 0x01, 0x07, 0xa1, 0x44, 0x03, 0x42, 0x00, 0x04, 0x79, 0x19, 0x2c, 0xb4, 0xa4, 0x15, 0xf8,
		0x54, 0x80, 0x32, 0xa0, 0x5a, 0xca, 0xa1, 0x64, 0x9e, 0x7d, 0xa7, 0x01, 0x0b, 0x1d, 0xb2, 0x1f,
		0xcc, 0x85, 0xd5, 0xfa, 0xb6, 0x21, 0xce, 0x4c, 0x01, 0x62, 0x9f, 0xfb, 0x14, 0x30, 0x54, 0x4c,
		0xca, 0xca, 0x4f, 0xb4, 0x8b, 0xbb, 0x62, 0xf9, 0x4a, 0x76, 0xc7, 0xb1, 0x84, 0x8d, 0x23, 0x3d,
		0x58, 0x5a, 0x61, 0x99, 0xf5, 0x8c, 0xa5, 0xa1, 0x66,
	};

	size_t der_len = 121;
	const unsigned char *der = data;
	EC_KEY *eckey = d2i_ECPrivateKey(NULL, (const unsigned char **)&der, der_len);
	if (!eckey) {
		fprintf(stderr, "d2i_ECPrivateKey() failed: %s\n", ERR_error_string(ERR_get_error(), NULL));
		return -1;
	}
	EC_KEY_free(eckey);

	return 0;
}
```

### Reproduction steps
Configure wolfSSL with this command and run the program.
```
./configure --enable-md4 --enable-des3 --enable-pwdbased --enable-wpas --enable-wpas-dpp  --enable-opensslall --enable-opensslextra --enable-dsa --enable-keying-material --disable-tls13
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SparkiDev**
# Description

d2i_ECPrivateKey() takes DER encoded data
Code was incorrectly using data as a private key instead of DER
decoding.

Please describe the scope of the fix or feature addition.

Fixes #5064

# Testing

See POC code in Issue.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by SparkiDev** [comment]
@julek-wolfssl
Did you have a use  case where the raw private key is passed in?

File: src/ssl.c [hunk 1]
```diff
@@ -32598,10 +32599,13 @@ WOLFSSL_EC_KEY *wolfSSL_d2i_ECPrivateKey(WOLFSSL_EC_KEY **key, const unsigned ch
...
-            (ecc_key*)eckey->internal) != MP_OKAY) {
-        WOLFSSL_MSG("wc_ecc_import_private_key error");
-        goto error;
+    if (wc_EccPrivateKeyDecode(*in, &idx, (ecc_key*)eckey->internal,
+            (word32)len) != 0) {
+        if (wc_ecc_import_private_key(*in, (word32)len, NULL, 0,
+                (ecc_key*)eckey->internal) != MP_OKAY) {
+            WOLFSSL_MSG("wc_ecc_import_private_key error");
+            goto error;
+        }
```
Comment (julek-wolfssl) [inline src/ssl.c:32608]: This should just be an error. We shouldn't attempt to read the raw key.

**Review by julek-wolfssl — CHANGES_REQUESTED** [review]

File: src/ssl.c (hunk 1 above)
Comment (SparkiDev) [reply src/ssl.c]: Fixed.
Changed i2d to encode into DER.

**Review by dgarske — APPROVED** [review]
