### PR TITLE
fix mp_read_unsigned_bin() calculation of mp_int.used_bits

### LINKED ISSUE #3539: Can mp_read_unsigned_bin / mp_to_unsigned_bin_at_pos support non-MP_8BIT?
Take mp_read_unsigned_bin for example, the following code will caue a->used to increase TOO fast, if it is not MP_8BIT. Later in clamp, the out of bound a->used will cause array out of bound.
Suggest to remove " a->used += xx" statement, and add a  "  a->used  = a-> alloc ; "  before  mp_clamp (a);

`int mp_read_unsigned_bin (mp_int * a, const unsigned char *b, int c)
{
  int     res;

  /* make sure there are at least two digits */
  if (a->alloc < 2) {
     if ((res = mp_grow(a, 2)) != MP_OKAY) {
        return res;
     }
  }

  /* zero the int */
  mp_zero (a);

  /* read the bytes in */
  while (c-- > 0) {
    if ((res = mp_mul_2d (a, 8, a)) != MP_OKAY) {
      return res;
    }

#ifndef MP_8BIT
      a->dp[0] |= *b++;
      a->used += 1;
#else
      a->dp[0] = (*b & MP_MASK);
      a->dp[1] |= ((*b++ >> 7U) & 1);
      a->used += 2;
#endif
  }
  mp_clamp (a);
  return MP_OKAY;
}`

### PR DESCRIPTION
**Pull request by douzzer**
Fixes #3539.

In the final iteration of the loop in `mp_read_unsigned_bin()`, the pessimistic full-digit increment of `a->used` could overshoot `a->alloc`, and since `mp_mul_2d()` wasn't called again, `mp_clamp()` could be entered with that in place, resulting in an out-of-bounds read of `a->dp`.

The fix is to initialize `a->used` in the first iteration to the count of digits used at that point, and let `mp_mul_2d()` increase `->used` thereafter in each iteration with correct bit-granularity logic.

As an optimization, the output buffer is enlarged at entry to be able to hold the supplied input.  This avoid calls to `realloc()` inside the loop.

### CODE REVIEW

File: wolfcrypt/src/integer.c [hunk 1]
```diff
@@ -716,11 +724,13 @@ int mp_read_unsigned_bin (mp_int * a, const unsigned char *b, int c)
 
 #ifndef MP_8BIT
       a->dp[0] |= *b++;
-      a->used += 1;
+      if (a->used == 0)
+          a->used = 1;
```
Comment (toddouska) [inline wolfcrypt/src/integer.c:728]: Is gets 1 correct?  What if c was 128 and now we're touching up the final element.  Wouldn't a->used be much bigger than 1?

**Review by dgarske — APPROVED** [review]
Excellent optimization! Thanks @douzzer

File: wolfcrypt/src/integer.c (hunk 1 above)
Comment (toddouska) [reply wolfcrypt/src/integer.c:728]: never mind, looks good.

**Review by toddouska — APPROVED** [review]

**Comment by douzzer** [comment]
> Excellent optimization! Thanks @douzzer

Credit to Sean for noticing the opportunity to avoid the reallocs.  We cooked up this fix jointly -- his very last contribution before 2 weeks of well-earned break.
